name: Feature request
description: Suggest an improvement
title: "[Feature]: "
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem or use case
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
    validations:
      required: true
  - type: input
    id: applications
    attributes:
      label: Relevant JACK applications
      placeholder: Ardour, REAPER, Carla
